language: node_js
node_js:
  - 9

cache:
  directories:
    - node_modules

script:
  - npm run postinstall

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  on:
    branch: master